name: Wallet Service

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - wallet-service/**

permissions:
  checks: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: 'maven'

      - name: Build and Test
        run: |
          mvn -B -f wallet-service/pom.xml clean install

      - name: Publish Unit Tests Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: 'wallet-service/target/surefire-reports/TEST-*.xml'
          check_name: Unit Test Report
          fail_on_test_failures: true

      - name: Publish Integration Tests Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: 'wallet-service/user-identity-service/target/failsafe-reports/TEST-*.xml'
          check_name: Integration Test Report
          fail_on_test_failures: true